---
- hosts: all
  strategy: free
  become: yes
  remote_user: root
  roles:
    - common    
    - role: gantsign.oh-my-zsh
      users:
        - username: root
          oh_my_zsh:
            theme: af-magic
            plugins:
              - git
  
