---
- name: Zabbix-Windows-Clients | Creating Directory for Installation Files
  ansible.windows.win_file:
          path: C:\Zabbix
          state: directory
- name: Zabbix-Windows-Clients | Sending Config File to Remote Hosts
  ansible.windows.win_template:
          src: roles/Client-Windows/templates/zabbix_agent.conf.j2
          dest: C:\Zabbix\zabbix_agent.conf
- name: Zabbix-Windows-Clients | Sending Installation File to Remote Hosts
  ansible.windows.win_copy:
          src: 'roles/Client-Windows/files/zabbix_agent.exe'
          dest: 'C:\Zabbix\zabbix_agent.exe'
- name: Zabbix-Windows-Clients | Installing Zabbix as Service
  ansible.windows.win_shell: |
          C:\Zabbix\zabbix_agent.exe -i -c C:\Zabbix\zabbix_agent.conf
