---
- hosts: lxc
  remote_user: root
  become: yes
  tasks:
    - name: Editing Resolv.conf
      lineinfile:
        path: /etc/resolvconf/resolv.conf.d/head
        regexp: '^namerserver.'
        insertafter: '.'
        line: "domain ramand.local \nsearch ramand.local \nnameserver 178.22.122.100 \nnameserver 185.51.200.2"
    - name: Updating ResolvConf
      raw: 'resolvconf -u'