---
- name: Linux Agent Setup
  hosts: Linux-Clients 
  remote_user: root
  roles:
          - Client-Linux
- name: Windows Agent Setup
  hosts: Windows-Clients
  gather_facts: false
  vars:
          ansible_user: "administrator@RAMAND.LOCAL"
          ansible_password: "RamandQAZ"
          ansible_connection: winrm
          ansible_winrm_transport: kerberos
          ansible_port: 5985
          #ansible_winrm_realm: "RAMAND.LOCAL"
          #ansible_winrm_kerberos_delegation: yes
  roles:
          - Client-Windows
