---
- hosts: NewTemplateInstances
  become: yes
  remote_user: root
  roles:
    - common    
    - role: gantsign.oh-my-zsh
      users:
        - username: root
          oh_my_zsh:
            theme: af-magic
            plugins:
              - git
              - zsh_reload
              - ubuntu
              - sudo
              - z
              - tmux
              - common-aliases
              - systemd  
